### Latihan 1
Membuat identitas diri menggunakan pemograman python sederhana

In [1]:
nama = "Alvian Totonafo Mendrofa"
nim = "20220801045"
fakultas = "Ilmu Komputer"
prodi = "Teknik Informatika"

print("Data Diri")
print("Nama     : "+nama)
print("NIM      : "+nim)
print("Fakultas : "+fakultas)
print("Prodi    : "+prodi)

Data Diri
Nama     : Alvian Totonafo Mendrofa
NIM      : 20220801045
Fakultas : Ilmu Komputer
Prodi    : Teknik Informatika


### Latihan 2
Membuat Matriks dengan ordo 3x3

In [2]:
matrice = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(matrice)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### Latihan 3
Membuat Matriks dengan ordo 5x5 dengan menambahkan library NumPy didalamnya

In [3]:
from numpy import *

matrice = range(25)
matrice = reshape(matrice, (5, 5))

print(matrice)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Latihan 4
Membuat Matriks dengan menggunakan Library NumPy dengan orde 3x20, dan nilai elemen dimulai dari indeks 1 sampai dengan 10 secara random

In [4]:
import numpy as np
from numpy import *

matrice = np.random.randint(1, 10, (3, 20))
print(matrice)

[[7 9 1 1 5 3 7 9 4 9 8 2 4 4 9 9 9 1 1 5]
 [6 1 2 7 4 1 1 8 5 6 8 2 6 3 4 8 9 1 2 3]
 [2 8 7 8 4 2 6 8 8 6 7 9 9 7 3 3 7 1 5 5]]
